language: python
python:
    - "2.7"
install:
    - echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' > /tmp/llvm.list
    - echo 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /tmp/llvm.list
    - sudo cp /tmp/llvm.list /etc/apt/sources.list.d/
    - rm /tmp/llvm.list
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install llvm-3.5
    - sudo apt-get install llvm-3.5-runtime libllvm3.5 llvm-3.5-dev llvm-3.5
    - sudo python setup.py install
script: ./test
